export const pateriserie = [{
    id: 1,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 2,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 3,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 4,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 5,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 6,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 1,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 7,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 8,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 9,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 10,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 11,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 12,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 13,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 14,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 15,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 16,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 17,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 18,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 19,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 20,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 21,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 22,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
},{
    id: 23,
    image: "../img/eclaire-chocolat-vanille.jpeg",
    titre: "eclaire chocolat et vanille",
    description: "les pâtissiers de l'époque l'auraient nommé ainsi parce qu'il se mangeait en un éclair ! Pas bête ^^ Ou alors, ce nom viendrait de la brillance du glaçage. Peut-être aussi que cela viendrait de sa forme qui rappellerait celle d'un éclair (bof, je ne suis pas convaincue).",
    prix: 1.5,
}]